Repository FindMyPetOrg/findmypet-frontend, pull requests merged in 2024-02, with the labels that each got.

#4 Feat/UI refinement dark mode tailwind
  public/logo.png
  public/lost.png
  public/vercel.svg
  src/app/(app)/@header/dashboard/page.js
  src/app/(app)/@header/default.js
  src/app/(app)/Navigation.js
  src/app/(app)/about/page.js
  src/app/(app)/dashboard/page.js
  src/app/(app)/home/page.js
  src/app/(app)/layout.js
  src/app/(app)/posts/page.js
  src/app/(auth)/AuthCard.js
  src/app/(auth)/forgot-password/page.js
  src/app/(auth)/layout.js
  src/app/(auth)/login/page.js
  src/app/(auth)/register/page.js
  src/app/(auth)/verify-email/page.js
  src/app/LoginLinks.js
  src/app/layout.js
  src/app/page.js
  src/components/ApplicationLogo.js
  src/components/Button.js
  src/components/Input.js
  src/components/Label.js
  src/components/NavLink.js
  src/components/ResponsiveNavLink.js
Labels: documentation, enhancement, good first issue, frontend

#7 [findmypet-frontend][added] integrated new User PM module
  .env.example
  package-lock.json
  package.json
  src/app/(app)/Navigation.js
  src/app/(app)/direct/[id]/page.js
  src/app/(app)/direct/page.js
  src/hooks/direct.js
  src/lib/echo.js
Labels: enhancement, frontend

#9 [findmypet-frontend][added] added new profile page for users
  package-lock.json
  package.json
  src/app/(app)/direct/[id]/page.js
  src/app/(app)/direct/page.js
  src/app/(app)/profile/[id]/page.js
  src/components/FileUploader.js
  src/hooks/auth.js
Labels: documentation, enhancement, good first issue, frontend

#12 Feat/posts page
  package-lock.json
  package.json
  public/dog.png
  src/app/(app)/Navigation.js
  src/app/(app)/dashboard/page.js
  src/app/(app)/home/page.js
  src/app/(app)/posts/_components/DisplayContent.js
  src/app/(app)/posts/_components/ImageCarousel.js
  src/app/(app)/posts/_components/LikeButton.js
  src/app/(app)/posts/_components/Reward.js
  src/app/(app)/posts/_components/TextEditor.js
  src/app/(app)/posts/_components/TypeSelector.js
  src/app/(app)/posts/_components/TypeTag.js
  src/app/(app)/posts/_components/map/DisplayLocation.js
  src/app/(app)/posts/_components/map/LocationPicker.js
  src/app/(app)/posts/_components/map/PostsMap.js
  src/app/(app)/posts/_components/post/LargePost.js
  src/app/(app)/posts/_components/post/PostModal.js
  src/app/(app)/posts/new/page.js
  src/app/(app)/posts/page.js
  src/app/(app)/posts/view/[id]/page.js
  src/app/(app)/profile/[id]/page.js
  src/app/(auth)/forgot-password/page.js
  src/app/(auth)/login/page.js
  src/app/(auth)/register/page.js
  src/app/(auth)/verify-email/page.js
  src/app/global.css
  src/app/page.js
  src/components/ApplicationLogo.js
  src/components/FlexCenterWrapper.js
  src/components/Input.js
  src/components/LabeledFlexWrapper.js
  src/components/Tags.js
  src/hooks/post.js
Labels: frontend

#15 chore added new feature for search by post
  src/app/(app)/Navigation.js
  src/app/(app)/posts/_components/post/LargePost.js
  src/app/(app)/search/page.js
Labels: documentation, enhancement, good first issue, frontend
